
name: ci-test-deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.8.8
      with:
       heroku_api_key: ${{secret.HREOKU_API_KEY}}
       heroku_email: ${{secret.HEROKU_EMAIL}}
       heroku_app_name: ${{secret.HEROKU_APP}}
